### ISSUE TITLE
adb version(1.0.29) is too old, "device offline" error

### ISSUE THREAD

**Issue by donly** [zonghai-li/adb-ios#1]
adb version(1.0.29) is too old to support Android 4.2 and above, would you please upgrade that, many thanks!

**Comment by zonghai-li** [comment]
Will do a test. Is it that the target android version is >= 4.2?

**Comment by donly** [comment]
Yes, since [1.0.30](https://github.com/android/platform_system_core/commit/d5fcafaf41f8ec90986c813f75ec78402096af2d), adb add public key auth support.

**Comment by zonghai-li** [comment]
Just did a test. I was trying to connect to an Android TV, with Android version 4.4, which looks like it's working fine.  I guess the authentication added is mostly for the USB mode. (and we don't support USB). Anyway, I will get around to updating it to some more recent version.

**Comment by donly** [comment]
Thanks for your test, I think the Android TV is a special class, when I adb connect to TV, it was't showing the Auth dialog.

Waiting for your upgrade,
Thank you, zonghai-li.

**Comment by Tz101** [comment]
Same problem, I tested with my Nexus 4 (android version 5.1), `adb connect` and `disconnect` is ok, but can't execute any command, it shows `device offline`.

**Comment by zonghai-li** [comment]
I've updated the adb to 1.0.32 (Android lollipop).  I don't have chance to take a thorough test due to lack of android devices available to me. Please help verify.

**Comment by donly** [comment]
Thanks zonghai-li, it  was work very well on my Android TV and Nexus 6.

When test with Nexus 6, may first enable [wireless adb](http://developer.android.com/tools/help/adb.html#wireless).

**Comment by sz-ashik440** [comment]
Hey, 
I am planning to update ADB to the [latest version](https://android.googlesource.com/platform/packages/modules/adb/). 
From your [source code](https://github.com/zonghai-li/adb-ios/tree/master/adb) I understood that you have added only server and client codes and removed daemon codes. 
It will be helpful if I can get some porting guidelines.

It's overdue but THANKS for your awesome port   🎉🎉🎉
