### ISSUE TITLE
Shell Keyevent to specific device

### ISSUE THREAD

**Issue by sz-ashik440** [zonghai-li/adb-ios#14]
I am trying to call shell command to a specific connected device. eg `adb -s 192.168.0.104 shell input keyevent 20`

What I found after reading `comandline.c` file, I have to call `adb_set_transport(ttype, serial);` before `adb_connect([NSString stringWithFormat:@"shell:%@", cmd].UTF8String);` command where `serial` is the IP address of the connected device.

But it failed to switch socket while calling `switch_socket_transport(int fd)`

_PS:_ I am struggling to understand most of the ADB source codes. Is there any documentation for ADB?

**Comment by thachonline** [comment]
@sz-ashik440 @zonghai-li 
Do you have any updates for this issue?

**Comment by sz-ashik440** [comment]
> @sz-ashik440 @zonghai-li Do you have any updates for this issue?

To connect to an IP, just call `connect:(NSString *) addr didResponse:(ResponseBlock)block` method from [/adb/ADBClient.h](https://github.com/zonghai-li/adb-ios/blob/master/adb/adb/AdbClient.m#L94).

And to send any key event call `shell:(NSString *)cmd didResponse:(ResponseBlock)block` method from [/adb/ADBClient.h](https://github.com/zonghai-li/adb-ios/blob/master/adb/adb/AdbClient.m#L249). Send cmd parameter string like this `input keyevent 20` 

PS:. first connect with connect command then send the shell cmd
